version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_ACCOUNT_ID - $AWS_DEFAULT_REGION - $IMAGE_REPO_NAME - $IMAGE_TAG
      - REPOSITORY_ENDPOINT=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - IMAGE=${REPOSITORY_ENDPOINT}/${IMAGE_REPO_NAME}
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${REPOSITORY_ENDPOINT}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE:${IMAGE_TAG} .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE:$IMAGE_TAG
      - echo Push completed on `date`
      - echo Writing image definitions file...
      - printf '{"name":"%s","ImageURI":"%s"}' $IMAGE_REPO_NAME $IMAGE:$IMAGE_TAG > imageDetail.json
      - ./generate-appspec.sh
      - ./generate-taskdef.sh
  artiartifacts:
    files:
      - imageDetail.json
      - taskdef.json
      - appspec.yaml
